# Generated by Django 4.1.4 on 2022-12-22 04:27

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип интереса')),
            ],
        ),
        migrations.CreateModel(
            name='DubStudioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='dub_studio/', verbose_name='Фото страницы студия дубляжа')),
                ('video', models.FileField(upload_to='dub_studio/', verbose_name='Видео страницы студия дубляжа')),
                ('first_text', models.CharField(max_length=100, verbose_name='Первый заголовок')),
                ('first_text_desc', models.TextField(verbose_name='Первое описание')),
                ('second_text', models.CharField(max_length=100, verbose_name='Второй заголовок')),
                ('second_text_desc', models.TextField(verbose_name='Второе описание')),
                ('third_text', models.CharField(max_length=100, verbose_name='Третий заголовок')),
                ('third_text_desc', models.TextField(verbose_name='Третье описание')),
                ('projects', models.CharField(default='Работы', max_length=100, verbose_name='Заголовок работы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_us', models.CharField(default='Напишите нам', max_length=100, verbose_name='Поле напишите нам')),
                ('interests', models.CharField(default='Что интересует?', max_length=100, verbose_name='Поле интересует')),
                ('about_u', models.CharField(default='О вас', max_length=100, verbose_name='Поле о вас')),
                ('company_name', models.CharField(default='JKS Entertainment', max_length=100, verbose_name='Название компании')),
                ('company_description', models.TextField(verbose_name='Описание компании')),
                ('tiktok_url', models.URLField(verbose_name='URL tiktoka')),
                ('instagram_url', models.URLField(verbose_name='URL instagram')),
                ('mail_field', models.CharField(max_length=100, verbose_name='Почта')),
                ('contact_info', models.CharField(default='Контактная информация:', max_length=100, verbose_name='Заголовок контактной информации')),
                ('services', models.CharField(default='Сервисы', max_length=100, verbose_name='Поле сервисы')),
                ('about_us', models.CharField(default='О нас', max_length=100, verbose_name='Поле о нас')),
                ('phone', models.CharField(max_length=20, verbose_name='Поле телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='gamedev/', verbose_name='Изображение игры')),
                ('preview', models.FileField(upload_to='gamedev/', verbose_name='Превью игры')),
                ('statistics', models.CharField(default='Статистика ', max_length=100, verbose_name='Заголовок статистики')),
                ('ios_statistics', models.CharField(max_length=100, verbose_name='IOS статистика')),
                ('ios', models.CharField(default='на ios', max_length=100, verbose_name='Заголовок IOS статистики')),
                ('android_statistics', models.CharField(max_length=100, verbose_name='Android статистика')),
                ('android', models.CharField(default='на android', max_length=100, verbose_name='Заголовок Android статистики')),
                ('urls', models.CharField(default='Найди каждому пару', max_length=100, verbose_name='Заголовок ссылок')),
                ('appstore_url', models.URLField(verbose_name='Ссылка на проект в AppStore')),
                ('googleplay_url', models.URLField(verbose_name='Ссылка на проект в GooglePlay')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.CharField(default='О нас', max_length=100, verbose_name='О нас')),
                ('projects', models.CharField(default='Проекты', max_length=100, verbose_name='Проекты')),
                ('contacts', models.CharField(default='Контакты', max_length=100, verbose_name='Контакты')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='header/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='influencer/', verbose_name='Логотип инфлюенсера/дома')),
                ('statistics', models.CharField(default='Статистика', max_length=100, verbose_name='Заголовок блока статистика')),
                ('instagram_statistics', models.CharField(default='В instagram', max_length=100, verbose_name='Заголовок статистика инстаграм')),
                ('instagram', models.CharField(default='1M', max_length=100, verbose_name='Статистика инстаграм')),
                ('tiktok_statistics', models.CharField(default='В tiktok', max_length=100, verbose_name='Заголовок статистика tiktok')),
                ('tiktok', models.CharField(default='26M', max_length=100, verbose_name='Статистика tiktok')),
                ('youtube_statistics', models.CharField(default='В youtube', max_length=100, verbose_name='Заголовок статистика youtube')),
                ('youtube', models.CharField(default='3.45K', max_length=100, verbose_name='Статистика youtube')),
                ('description', models.TextField(verbose_name='Описание инфлюенсера/дома')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='main/', verbose_name='Фото главной страницы')),
                ('main_video', models.FileField(upload_to='main/', verbose_name='Видео главной страницы')),
                ('who_are_we', models.CharField(default='Кто мы?', max_length=100, verbose_name='Поле кто мы')),
                ('who_are_we_desc', models.TextField(verbose_name='Кто мы описание')),
                ('learn_more', models.CharField(default='Узнать больше', max_length=100, verbose_name='Поле узнать больше')),
                ('projects', models.CharField(default='Проекты', max_length=100, verbose_name='Поле проекты')),
                ('statistics', models.CharField(default='Цифры громче слов', max_length=100, verbose_name='Заголовок статистики')),
                ('influencers', models.CharField(default='Инфлюенсеров', max_length=100, verbose_name='Заголовок инфлюенсеров')),
                ('influencers_info', models.CharField(default='25+', max_length=100, verbose_name='Значение инфлюенсеров')),
                ('subscribers', models.CharField(default='Подписчиков', max_length=100, verbose_name='Заголовок подписчиков')),
                ('subscribers_info', models.CharField(default='200м+', max_length=100, verbose_name='Значение подписчиков')),
                ('likes', models.CharField(default='Лайков в тиктоке', max_length=100, verbose_name='Заголовок лайков')),
                ('likes_info', models.CharField(default='5млрд+', max_length=100, verbose_name='Значение лайков')),
                ('views', models.CharField(default='Просмотров в месяц', max_length=100, verbose_name='Заголовок просмотров')),
                ('views_info', models.CharField(default='1млрд', max_length=100, verbose_name='Значение просмотров')),
                ('partners', models.CharField(default='Партнеры', max_length=100, verbose_name='Заголовок партнеры')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('age', models.CharField(default='Возраст: ', max_length=100, verbose_name='Возраст')),
                ('series_number', models.CharField(default='Кол-во серий: ', max_length=100, verbose_name='Кол-во серий')),
                ('language', models.CharField(default='Язык: ', max_length=100, verbose_name='Язык')),
                ('genre', models.CharField(default='Жанр: ', max_length=100, verbose_name='Жанр')),
                ('button', models.CharField(default='Смотреть сейчас', max_length=100, verbose_name='Кнопка смотреть сейчас')),
                ('url', models.URLField(verbose_name='Ссылка на проект')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='dub_studio/', verbose_name='Логотип студии')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jks_site.dubstudiopage')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя переводившего')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='dub_studio/', verbose_name='Фото переводившего')),
                ('voice', models.FileField(upload_to='dub_studio/', verbose_name='Запись голоса')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jks_site.studio', verbose_name='Отношение к студии')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProductionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Видеопродакшн', max_length=100, verbose_name='Заголовок страницы')),
                ('what_we_filming', models.CharField(default='Что мы снимаем', max_length=100, verbose_name='Заголовок что мы снимаем')),
                ('first_product', models.CharField(default='Видео для социальных сетей', max_length=100, verbose_name='Заголовок первой услуги')),
                ('first_product_desc', models.TextField(verbose_name='Описание первой услуги')),
                ('second_product', models.CharField(default='Среднемасштабный продакшн', max_length=100, verbose_name='Заголовок первой услуги')),
                ('second_product_desc', models.TextField(verbose_name='Описание первой услуги')),
                ('third_product', models.CharField(default='Крупномасштабный продакшн', max_length=100, verbose_name='Заголовок первой услуги')),
                ('third_product_desc', models.TextField(verbose_name='Описание первой услуги')),
                ('fourth_product', models.CharField(default='Анимация (CGI)', max_length=100, verbose_name='Заголовок первой услуги')),
                ('fourth_product_desc', models.TextField(verbose_name='Описание первой услуги')),
                ('offer', models.TextField(verbose_name='Предложение')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesFilmsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='series/', verbose_name='Изображение страницы')),
                ('title', models.CharField(default='Королева двора', max_length=100, verbose_name='Заголовок проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('projects', models.CharField(default='Работы', max_length=100, verbose_name='Заголовок работы')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Проекты', max_length=255, verbose_name='Заголовок страницы проекты')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('projects_foto', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='projects/', verbose_name='Фото проекта')),
                ('projects_video', models.FileField(upload_to='projects/')),
                ('main_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.mainpage')),
                ('project_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.projectspage')),
            ],
        ),
        migrations.CreateModel(
            name='InfluncerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='influencer/', verbose_name='Фото инфлюенсера')),
                ('description', models.TextField(verbose_name='Описание под фото')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jks_site.influencer', verbose_name='Отношение к инфлюенсеру')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Инфлюенсеры', max_length=255, verbose_name='Заголовок страницы инфлюенсеры')),
                ('first_text', models.CharField(default='Крупнейшие TikTok-хаусы и лучшие блогеры', max_length=255, verbose_name='Первый текст')),
                ('second_text', models.CharField(default='Более 300 млн подписчиков', max_length=255, verbose_name='Второй текст')),
                ('third_text', models.CharField(default='6 серебряных и 2 золотых кнопки YouTube', max_length=255, verbose_name='Третий текст')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfluencerMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя участника дома')),
                ('instagram_statistics', models.CharField(default='В instagram', max_length=100, verbose_name='Заголовок статистика инстаграм')),
                ('instagram', models.CharField(max_length=100, verbose_name='Статистика инстаграм')),
                ('tiktok_statistics', models.CharField(default='В tiktok', max_length=100, verbose_name='Заголовок статистика tiktok')),
                ('tiktok', models.CharField(max_length=100, verbose_name='Статистика tiktok')),
                ('youtube_statistics', models.CharField(default='В youtube', max_length=100, verbose_name='Заголовок статистика youtube')),
                ('youtube', models.CharField(max_length=100, verbose_name='Статистика youtube')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='influencer/', verbose_name='Фото участника дома')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jks_site.influencer', verbose_name='Отношение к дому')),
            ],
        ),
        migrations.AddField(
            model_name='influencer',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jks_site.influencerspage'),
        ),
        migrations.CreateModel(
            name='GameDevPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Разработка игр', max_length=255, verbose_name='Заголовок страницы разработка игр')),
                ('first_text', models.CharField(max_length=100, verbose_name='Первый заголовок')),
                ('first_text_desc', models.TextField(verbose_name='Первое описание')),
                ('second_text', models.CharField(max_length=100, verbose_name='Второй заголовок')),
                ('second_text_desc', models.TextField(verbose_name='Первое описание')),
                ('third_text', models.CharField(max_length=100, verbose_name='Третий заголовок')),
                ('third_text_desc', models.TextField(verbose_name='Первое описание')),
                ('photo_background1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='game_dev/', verbose_name='Фото подложки 1')),
                ('photo_background2', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='game_dev/', verbose_name='Фото подложки 2')),
                ('photo_background3', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='game_dev/', verbose_name='Фото подложки 3')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.choices')),
            ],
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер'),
        ),
        migrations.CreateModel(
            name='DubSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='dub_projects/', verbose_name='Фото проекта')),
                ('preview', models.FileField(upload_to='dub_projects/', verbose_name='Превью проекта')),
                ('dub_language', models.CharField(default='Язык дубляжа: ', max_length=255, verbose_name='Язык дубляжа')),
                ('translated_by', models.CharField(default='Перевели: ', max_length=100, verbose_name='Кто перевел')),
                ('button', models.CharField(default='Смотреть сейчас', max_length=100, verbose_name='Текст кнопки')),
                ('url', models.URLField(verbose_name='Ссылка на проект')),
                ('total_series', models.CharField(default='Всего серий: ', max_length=100, verbose_name='Всего серий')),
                ('dub_series', models.CharField(default='Озвучено: ', max_length=100, verbose_name='Озвучено')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jks_site.dubstudiopage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DubMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='dub_projects/', verbose_name='Фото проекта')),
                ('preview', models.FileField(upload_to='dub_projects/', verbose_name='Превью проекта')),
                ('dub_language', models.CharField(default='Язык дубляжа: ', max_length=255, verbose_name='Язык дубляжа')),
                ('translated_by', models.CharField(default='Перевели: ', max_length=100, verbose_name='Кто перевел')),
                ('button', models.CharField(default='Смотреть сейчас', max_length=100, verbose_name='Текст кнопки')),
                ('url', models.URLField(verbose_name='Ссылка на проект')),
                ('duration', models.CharField(default='Длительность: ', max_length=100, verbose_name='Длительность')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jks_site.dubstudiopage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='main/', verbose_name='Фото для страницы видеопродакшн')),
                ('content_video', models.FileField(blank=True, default=None, null=True, upload_to='video_prod_cont/', verbose_name='Видео для страницы видеопродакшн')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.videoproductionpage')),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer'),
        ),
        migrations.CreateModel(
            name='AnimationStudioPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Студия анимации', max_length=100, verbose_name='Заголовок страницы студия анимации')),
                ('field', models.CharField(default='Coming soon', max_length=100, verbose_name='Заглушка')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ВАЙНЕРЫ? УЖЕ НЕТ. JKS- ЭТО МЕДИАКОМПАНИЯ.', max_length=255, verbose_name='Заголовок страницы о нас')),
                ('first_text', models.TextField(verbose_name='Первый текст')),
                ('second_text', models.TextField(verbose_name='Второй текст')),
                ('third_text', models.TextField(verbose_name='Третий текст')),
                ('fourth_text', models.TextField(verbose_name='Четвертый текст')),
                ('fifth_text', models.TextField(verbose_name='Пятый текст')),
                ('sixth_text', models.TextField(verbose_name='Шестой текст')),
                ('seventh_text', models.TextField(verbose_name='Седьмой текст')),
                ('eighth_text', models.TextField(verbose_name='Восьмой текст')),
                ('photo_background1', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_us/', verbose_name='Фото подложки 1')),
                ('photo_background2', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_us/', verbose_name='Фото подложки 2')),
                ('photo_background3', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_us/', verbose_name='Фото подложки 3')),
                ('photo_background4', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_us/', verbose_name='Фото подложки 4')),
                ('photo_background5', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_us/', verbose_name='Фото подложки 5')),
                ('photo_background6', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='about_us/', verbose_name='Фото подложки 6')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
