# Generated by Django 4.1.4 on 2022-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product',
            field=models.CharField(default='Анимация (CGI)', max_length=100, verbose_name='Заголовок четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product_desc',
            field=models.TextField(verbose_name='Описание четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product_desc_en',
            field=models.TextField(null=True, verbose_name='Описание четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product_en',
            field=models.CharField(default='Анимация (CGI)', max_length=100, null=True, verbose_name='Заголовок четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product_kk',
            field=models.CharField(default='Анимация (CGI)', max_length=100, null=True, verbose_name='Заголовок четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='fourth_product_ru',
            field=models.CharField(default='Анимация (CGI)', max_length=100, null=True, verbose_name='Заголовок четвертой услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product',
            field=models.CharField(default='Среднемасштабный продакшн', max_length=100, verbose_name='Заголовок второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product_desc',
            field=models.TextField(verbose_name='Описание второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product_desc_en',
            field=models.TextField(null=True, verbose_name='Описание второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product_en',
            field=models.CharField(default='Среднемасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product_kk',
            field=models.CharField(default='Среднемасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='second_product_ru',
            field=models.CharField(default='Среднемасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок второй услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product',
            field=models.CharField(default='Крупномасштабный продакшн', max_length=100, verbose_name='Заголовок третьей услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product_desc',
            field=models.TextField(verbose_name='Описание третьей услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product_desc_en',
            field=models.TextField(null=True, verbose_name='Описание третьей услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание третьей услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание третьей услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product_en',
            field=models.CharField(default='Крупномасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок третьей услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product_kk',
            field=models.CharField(default='Крупномасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок третьей услуги'),
        ),
        migrations.AlterField(
            model_name='videoproductionpage',
            name='third_product_ru',
            field=models.CharField(default='Крупномасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок третьей услуги'),
        ),
    ]
