# Generated by Django 4.1.4 on 2022-12-22 05:43

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='preview',
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='partner/', verbose_name='Лого партнера')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.mainpage')),
            ],
        ),
    ]
