# Generated by Django 4.1.4 on 2022-12-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0004_alter_influencer_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя/название дома'),
        ),
    ]
