# Generated by Django 4.1.4 on 2022-12-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0005_influencer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='instagram',
            field=models.CharField(blank=True, default='1M', max_length=100, null=True, verbose_name='Статистика инстаграм'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='instagram_statistics',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='tiktok',
            field=models.CharField(blank=True, default='26M', max_length=100, null=True, verbose_name='Статистика tiktok'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='tiktok_statistics',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='youtube',
            field=models.CharField(blank=True, default='3.45K', max_length=100, null=True, verbose_name='Статистика youtube'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='youtube_statistics',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
        migrations.AlterField(
            model_name='influencermembers',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статистика инстаграм'),
        ),
        migrations.AlterField(
            model_name='influencermembers',
            name='instagram_statistics',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AlterField(
            model_name='influencermembers',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статистика tiktok'),
        ),
        migrations.AlterField(
            model_name='influencermembers',
            name='tiktok_statistics',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AlterField(
            model_name='influencermembers',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статистика youtube'),
        ),
        migrations.AlterField(
            model_name='influencermembers',
            name='youtube_statistics',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
    ]
