# Generated by Django 4.1.4 on 2022-12-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0007_alter_influencer_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubmovies',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_projects', to='jks_site.dubstudiopage'),
        ),
        migrations.AlterField(
            model_name='dubseries',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_projects', to='jks_site.dubstudiopage'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='jks_site.dubstudiopage'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='jks_site.studio', verbose_name='Отношение к студии'),
        ),
    ]
