# Generated by Django 4.1.4 on 2022-12-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0008_alter_dubmovies_page_alter_dubseries_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesfilms',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_films', to='jks_site.seriesfilmspage'),
        ),
    ]
