# Generated by Django 4.1.4 on 2022-12-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0009_seriesfilms_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='jks_site.gamedevpage'),
        ),
        migrations.AlterField(
            model_name='seriesfilms',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_films', to='jks_site.seriesfilmspage'),
        ),
    ]
