# Generated by Django 4.1.4 on 2022-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0010_game_page_alter_seriesfilms_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedevpage',
            name='third_text',
        ),
        migrations.RemoveField(
            model_name='gamedevpage',
            name='third_text_desc',
        ),
        migrations.AlterField(
            model_name='gamedevpage',
            name='second_text_desc',
            field=models.TextField(verbose_name='Второе описание'),
        ),
    ]
