# Generated by Django 4.1.4 on 2022-12-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0012_rename_urls_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя менеджера')),
                ('email', models.CharField(max_length=100, verbose_name='Email для отправки писем')),
            ],
        ),
    ]
