# Generated by Django 4.1.4 on 2022-12-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0013_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='eighth_text_en',
            field=models.TextField(null=True, verbose_name='Восьмой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='eighth_text_kk',
            field=models.TextField(null=True, verbose_name='Восьмой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='eighth_text_ru',
            field=models.TextField(null=True, verbose_name='Восьмой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='fifth_text_en',
            field=models.TextField(null=True, verbose_name='Пятый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='fifth_text_kk',
            field=models.TextField(null=True, verbose_name='Пятый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='fifth_text_ru',
            field=models.TextField(null=True, verbose_name='Пятый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='first_text_en',
            field=models.TextField(null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='first_text_kk',
            field=models.TextField(null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='first_text_ru',
            field=models.TextField(null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='fourth_text_en',
            field=models.TextField(null=True, verbose_name='Четвертый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='fourth_text_kk',
            field=models.TextField(null=True, verbose_name='Четвертый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='fourth_text_ru',
            field=models.TextField(null=True, verbose_name='Четвертый текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='second_text_en',
            field=models.TextField(null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='second_text_kk',
            field=models.TextField(null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='second_text_ru',
            field=models.TextField(null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='seventh_text_en',
            field=models.TextField(null=True, verbose_name='Седьмой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='seventh_text_kk',
            field=models.TextField(null=True, verbose_name='Седьмой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='seventh_text_ru',
            field=models.TextField(null=True, verbose_name='Седьмой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='sixth_text_en',
            field=models.TextField(null=True, verbose_name='Шестой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='sixth_text_kk',
            field=models.TextField(null=True, verbose_name='Шестой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='sixth_text_ru',
            field=models.TextField(null=True, verbose_name='Шестой текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='third_text_en',
            field=models.TextField(null=True, verbose_name='Третий текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='third_text_kk',
            field=models.TextField(null=True, verbose_name='Третий текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='third_text_ru',
            field=models.TextField(null=True, verbose_name='Третий текст'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='title_en',
            field=models.CharField(default='ВАЙНЕРЫ? УЖЕ НЕТ. JKS- ЭТО МЕДИАКОМПАНИЯ.', max_length=255, null=True, verbose_name='Заголовок страницы о нас'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='title_kk',
            field=models.CharField(default='ВАЙНЕРЫ? УЖЕ НЕТ. JKS- ЭТО МЕДИАКОМПАНИЯ.', max_length=255, null=True, verbose_name='Заголовок страницы о нас'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='title_ru',
            field=models.CharField(default='ВАЙНЕРЫ? УЖЕ НЕТ. JKS- ЭТО МЕДИАКОМПАНИЯ.', max_length=255, null=True, verbose_name='Заголовок страницы о нас'),
        ),
        migrations.AddField(
            model_name='animationstudiopage',
            name='field_en',
            field=models.CharField(default='Coming soon', max_length=100, null=True, verbose_name='Заглушка'),
        ),
        migrations.AddField(
            model_name='animationstudiopage',
            name='field_kk',
            field=models.CharField(default='Coming soon', max_length=100, null=True, verbose_name='Заглушка'),
        ),
        migrations.AddField(
            model_name='animationstudiopage',
            name='field_ru',
            field=models.CharField(default='Coming soon', max_length=100, null=True, verbose_name='Заглушка'),
        ),
        migrations.AddField(
            model_name='animationstudiopage',
            name='title_en',
            field=models.CharField(default='Студия анимации', max_length=100, null=True, verbose_name='Заголовок страницы студия анимации'),
        ),
        migrations.AddField(
            model_name='animationstudiopage',
            name='title_kk',
            field=models.CharField(default='Студия анимации', max_length=100, null=True, verbose_name='Заголовок страницы студия анимации'),
        ),
        migrations.AddField(
            model_name='animationstudiopage',
            name='title_ru',
            field=models.CharField(default='Студия анимации', max_length=100, null=True, verbose_name='Заголовок страницы студия анимации'),
        ),
        migrations.AddField(
            model_name='choices',
            name='type_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип интереса'),
        ),
        migrations.AddField(
            model_name='choices',
            name='type_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип интереса'),
        ),
        migrations.AddField(
            model_name='choices',
            name='type_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип интереса'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='button_en',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='button_kk',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='button_ru',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='dub_language_en',
            field=models.CharField(default='Язык дубляжа: ', max_length=255, null=True, verbose_name='Язык дубляжа'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='dub_language_kk',
            field=models.CharField(default='Язык дубляжа: ', max_length=255, null=True, verbose_name='Язык дубляжа'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='dub_language_ru',
            field=models.CharField(default='Язык дубляжа: ', max_length=255, null=True, verbose_name='Язык дубляжа'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='duration_en',
            field=models.CharField(default='Длительность: ', max_length=100, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='duration_kk',
            field=models.CharField(default='Длительность: ', max_length=100, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='duration_ru',
            field=models.CharField(default='Длительность: ', max_length=100, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='translated_by_en',
            field=models.CharField(default='Перевели: ', max_length=100, null=True, verbose_name='Кто перевел'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='translated_by_kk',
            field=models.CharField(default='Перевели: ', max_length=100, null=True, verbose_name='Кто перевел'),
        ),
        migrations.AddField(
            model_name='dubmovies',
            name='translated_by_ru',
            field=models.CharField(default='Перевели: ', max_length=100, null=True, verbose_name='Кто перевел'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='button_en',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='button_kk',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='button_ru',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='dub_language_en',
            field=models.CharField(default='Язык дубляжа: ', max_length=255, null=True, verbose_name='Язык дубляжа'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='dub_language_kk',
            field=models.CharField(default='Язык дубляжа: ', max_length=255, null=True, verbose_name='Язык дубляжа'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='dub_language_ru',
            field=models.CharField(default='Язык дубляжа: ', max_length=255, null=True, verbose_name='Язык дубляжа'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='dub_series_en',
            field=models.CharField(default='Озвучено: ', max_length=100, null=True, verbose_name='Озвучено'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='dub_series_kk',
            field=models.CharField(default='Озвучено: ', max_length=100, null=True, verbose_name='Озвучено'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='dub_series_ru',
            field=models.CharField(default='Озвучено: ', max_length=100, null=True, verbose_name='Озвучено'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='total_series_en',
            field=models.CharField(default='Всего серий: ', max_length=100, null=True, verbose_name='Всего серий'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='total_series_kk',
            field=models.CharField(default='Всего серий: ', max_length=100, null=True, verbose_name='Всего серий'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='total_series_ru',
            field=models.CharField(default='Всего серий: ', max_length=100, null=True, verbose_name='Всего серий'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='translated_by_en',
            field=models.CharField(default='Перевели: ', max_length=100, null=True, verbose_name='Кто перевел'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='translated_by_kk',
            field=models.CharField(default='Перевели: ', max_length=100, null=True, verbose_name='Кто перевел'),
        ),
        migrations.AddField(
            model_name='dubseries',
            name='translated_by_ru',
            field=models.CharField(default='Перевели: ', max_length=100, null=True, verbose_name='Кто перевел'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='first_text_desc_en',
            field=models.TextField(null=True, verbose_name='Первое описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='first_text_desc_kk',
            field=models.TextField(null=True, verbose_name='Первое описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='first_text_desc_ru',
            field=models.TextField(null=True, verbose_name='Первое описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='first_text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='first_text_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='first_text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='projects_en',
            field=models.CharField(default='Работы', max_length=100, null=True, verbose_name='Заголовок работы'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='projects_kk',
            field=models.CharField(default='Работы', max_length=100, null=True, verbose_name='Заголовок работы'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='projects_ru',
            field=models.CharField(default='Работы', max_length=100, null=True, verbose_name='Заголовок работы'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='second_text_desc_en',
            field=models.TextField(null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='second_text_desc_kk',
            field=models.TextField(null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='second_text_desc_ru',
            field=models.TextField(null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='second_text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='second_text_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='second_text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='third_text_desc_en',
            field=models.TextField(null=True, verbose_name='Третье описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='third_text_desc_kk',
            field=models.TextField(null=True, verbose_name='Третье описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='third_text_desc_ru',
            field=models.TextField(null=True, verbose_name='Третье описание'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='third_text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Третий заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='third_text_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Третий заголовок'),
        ),
        migrations.AddField(
            model_name='dubstudiopage',
            name='third_text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Третий заголовок'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_u_en',
            field=models.CharField(default='О вас', max_length=100, null=True, verbose_name='Поле о вас'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_u_kk',
            field=models.CharField(default='О вас', max_length=100, null=True, verbose_name='Поле о вас'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_u_ru',
            field=models.CharField(default='О вас', max_length=100, null=True, verbose_name='Поле о вас'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_en',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='Поле о нас'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_kk',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='Поле о нас'),
        ),
        migrations.AddField(
            model_name='footer',
            name='about_us_ru',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='Поле о нас'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_description_en',
            field=models.TextField(null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_description_kk',
            field=models.TextField(null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_description_ru',
            field=models.TextField(null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_name_en',
            field=models.CharField(default='JKS Entertainment', max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_name_kk',
            field=models.CharField(default='JKS Entertainment', max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_name_ru',
            field=models.CharField(default='JKS Entertainment', max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_info_en',
            field=models.CharField(default='Контактная информация:', max_length=100, null=True, verbose_name='Заголовок контактной информации'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_info_kk',
            field=models.CharField(default='Контактная информация:', max_length=100, null=True, verbose_name='Заголовок контактной информации'),
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_info_ru',
            field=models.CharField(default='Контактная информация:', max_length=100, null=True, verbose_name='Заголовок контактной информации'),
        ),
        migrations.AddField(
            model_name='footer',
            name='interests_en',
            field=models.CharField(default='Что интересует?', max_length=100, null=True, verbose_name='Поле интересует'),
        ),
        migrations.AddField(
            model_name='footer',
            name='interests_kk',
            field=models.CharField(default='Что интересует?', max_length=100, null=True, verbose_name='Поле интересует'),
        ),
        migrations.AddField(
            model_name='footer',
            name='interests_ru',
            field=models.CharField(default='Что интересует?', max_length=100, null=True, verbose_name='Поле интересует'),
        ),
        migrations.AddField(
            model_name='footer',
            name='services_en',
            field=models.CharField(default='Сервисы', max_length=100, null=True, verbose_name='Поле сервисы'),
        ),
        migrations.AddField(
            model_name='footer',
            name='services_kk',
            field=models.CharField(default='Сервисы', max_length=100, null=True, verbose_name='Поле сервисы'),
        ),
        migrations.AddField(
            model_name='footer',
            name='services_ru',
            field=models.CharField(default='Сервисы', max_length=100, null=True, verbose_name='Поле сервисы'),
        ),
        migrations.AddField(
            model_name='footer',
            name='text_us_en',
            field=models.CharField(default='Напишите нам', max_length=100, null=True, verbose_name='Поле напишите нам'),
        ),
        migrations.AddField(
            model_name='footer',
            name='text_us_kk',
            field=models.CharField(default='Напишите нам', max_length=100, null=True, verbose_name='Поле напишите нам'),
        ),
        migrations.AddField(
            model_name='footer',
            name='text_us_ru',
            field=models.CharField(default='Напишите нам', max_length=100, null=True, verbose_name='Поле напишите нам'),
        ),
        migrations.AddField(
            model_name='game',
            name='android_en',
            field=models.CharField(default='на android', max_length=100, null=True, verbose_name='Заголовок Android статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='android_kk',
            field=models.CharField(default='на android', max_length=100, null=True, verbose_name='Заголовок Android статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='android_ru',
            field=models.CharField(default='на android', max_length=100, null=True, verbose_name='Заголовок Android статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='ios_en',
            field=models.CharField(default='на ios', max_length=100, null=True, verbose_name='Заголовок IOS статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='ios_kk',
            field=models.CharField(default='на ios', max_length=100, null=True, verbose_name='Заголовок IOS статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='ios_ru',
            field=models.CharField(default='на ios', max_length=100, null=True, verbose_name='Заголовок IOS статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='statistics_en',
            field=models.CharField(default='Статистика ', max_length=100, null=True, verbose_name='Заголовок статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='statistics_kk',
            field=models.CharField(default='Статистика ', max_length=100, null=True, verbose_name='Заголовок статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='statistics_ru',
            field=models.CharField(default='Статистика ', max_length=100, null=True, verbose_name='Заголовок статистики'),
        ),
        migrations.AddField(
            model_name='game',
            name='title_en',
            field=models.CharField(default='Найди каждому пару', max_length=100, null=True, verbose_name='Заголовок ссылок'),
        ),
        migrations.AddField(
            model_name='game',
            name='title_kk',
            field=models.CharField(default='Найди каждому пару', max_length=100, null=True, verbose_name='Заголовок ссылок'),
        ),
        migrations.AddField(
            model_name='game',
            name='title_ru',
            field=models.CharField(default='Найди каждому пару', max_length=100, null=True, verbose_name='Заголовок ссылок'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='first_text_desc_en',
            field=models.TextField(null=True, verbose_name='Первое описание'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='first_text_desc_kk',
            field=models.TextField(null=True, verbose_name='Первое описание'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='first_text_desc_ru',
            field=models.TextField(null=True, verbose_name='Первое описание'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='first_text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='first_text_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='first_text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='second_text_desc_en',
            field=models.TextField(null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='second_text_desc_kk',
            field=models.TextField(null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='second_text_desc_ru',
            field=models.TextField(null=True, verbose_name='Второе описание'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='second_text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='second_text_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='second_text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='title_en',
            field=models.CharField(default='Разработка игр', max_length=255, null=True, verbose_name='Заголовок страницы разработка игр'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='title_kk',
            field=models.CharField(default='Разработка игр', max_length=255, null=True, verbose_name='Заголовок страницы разработка игр'),
        ),
        migrations.AddField(
            model_name='gamedevpage',
            name='title_ru',
            field=models.CharField(default='Разработка игр', max_length=255, null=True, verbose_name='Заголовок страницы разработка игр'),
        ),
        migrations.AddField(
            model_name='header',
            name='about_us_en',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='header',
            name='about_us_kk',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='header',
            name='about_us_ru',
            field=models.CharField(default='О нас', max_length=100, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='header',
            name='contacts_en',
            field=models.CharField(default='Контакты', max_length=100, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='header',
            name='contacts_kk',
            field=models.CharField(default='Контакты', max_length=100, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='header',
            name='contacts_ru',
            field=models.CharField(default='Контакты', max_length=100, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='header',
            name='projects_en',
            field=models.CharField(default='Проекты', max_length=100, null=True, verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='header',
            name='projects_kk',
            field=models.CharField(default='Проекты', max_length=100, null=True, verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='header',
            name='projects_ru',
            field=models.CharField(default='Проекты', max_length=100, null=True, verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание инфлюенсера/дома'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание инфлюенсера/дома'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание инфлюенсера/дома'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_statistics_en',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_statistics_kk',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_statistics_ru',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='name_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Имя/название дома'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='name_kk',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Имя/название дома'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='name_ru',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Имя/название дома'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='statistics_en',
            field=models.CharField(default='Статистика', max_length=100, null=True, verbose_name='Заголовок блока статистика'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='statistics_kk',
            field=models.CharField(default='Статистика', max_length=100, null=True, verbose_name='Заголовок блока статистика'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='statistics_ru',
            field=models.CharField(default='Статистика', max_length=100, null=True, verbose_name='Заголовок блока статистика'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_statistics_en',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_statistics_kk',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='tiktok_statistics_ru',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_statistics_en',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_statistics_kk',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='youtube_statistics_ru',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='instagram_statistics_en',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='instagram_statistics_kk',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='instagram_statistics_ru',
            field=models.CharField(blank=True, default='В instagram', max_length=100, null=True, verbose_name='Заголовок статистика инстаграм'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя участника дома'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя участника дома'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя участника дома'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='tiktok_statistics_en',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='tiktok_statistics_kk',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='tiktok_statistics_ru',
            field=models.CharField(blank=True, default='В tiktok', max_length=100, null=True, verbose_name='Заголовок статистика tiktok'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='youtube_statistics_en',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='youtube_statistics_kk',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
        migrations.AddField(
            model_name='influencermembers',
            name='youtube_statistics_ru',
            field=models.CharField(blank=True, default='В youtube', max_length=100, null=True, verbose_name='Заголовок статистика youtube'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='first_text_en',
            field=models.CharField(default='Крупнейшие TikTok-хаусы и лучшие блогеры', max_length=255, null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='first_text_kk',
            field=models.CharField(default='Крупнейшие TikTok-хаусы и лучшие блогеры', max_length=255, null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='first_text_ru',
            field=models.CharField(default='Крупнейшие TikTok-хаусы и лучшие блогеры', max_length=255, null=True, verbose_name='Первый текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='second_text_en',
            field=models.CharField(default='Более 300 млн подписчиков', max_length=255, null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='second_text_kk',
            field=models.CharField(default='Более 300 млн подписчиков', max_length=255, null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='second_text_ru',
            field=models.CharField(default='Более 300 млн подписчиков', max_length=255, null=True, verbose_name='Второй текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='third_text_en',
            field=models.CharField(default='6 серебряных и 2 золотых кнопки YouTube', max_length=255, null=True, verbose_name='Третий текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='third_text_kk',
            field=models.CharField(default='6 серебряных и 2 золотых кнопки YouTube', max_length=255, null=True, verbose_name='Третий текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='third_text_ru',
            field=models.CharField(default='6 серебряных и 2 золотых кнопки YouTube', max_length=255, null=True, verbose_name='Третий текст'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='title_en',
            field=models.CharField(default='Инфлюенсеры', max_length=255, null=True, verbose_name='Заголовок страницы инфлюенсеры'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='title_kk',
            field=models.CharField(default='Инфлюенсеры', max_length=255, null=True, verbose_name='Заголовок страницы инфлюенсеры'),
        ),
        migrations.AddField(
            model_name='influencerspage',
            name='title_ru',
            field=models.CharField(default='Инфлюенсеры', max_length=255, null=True, verbose_name='Заголовок страницы инфлюенсеры'),
        ),
        migrations.AddField(
            model_name='influncerphoto',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание под фото'),
        ),
        migrations.AddField(
            model_name='influncerphoto',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание под фото'),
        ),
        migrations.AddField(
            model_name='influncerphoto',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание под фото'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='influencers_en',
            field=models.CharField(default='Инфлюенсеров', max_length=100, null=True, verbose_name='Заголовок инфлюенсеров'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='influencers_kk',
            field=models.CharField(default='Инфлюенсеров', max_length=100, null=True, verbose_name='Заголовок инфлюенсеров'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='influencers_ru',
            field=models.CharField(default='Инфлюенсеров', max_length=100, null=True, verbose_name='Заголовок инфлюенсеров'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='learn_more_en',
            field=models.CharField(default='Узнать больше', max_length=100, null=True, verbose_name='Кнопка узнать больше'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='learn_more_kk',
            field=models.CharField(default='Узнать больше', max_length=100, null=True, verbose_name='Кнопка узнать больше'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='learn_more_ru',
            field=models.CharField(default='Узнать больше', max_length=100, null=True, verbose_name='Кнопка узнать больше'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='likes_en',
            field=models.CharField(default='Лайков в тиктоке', max_length=100, null=True, verbose_name='Заголовок лайков'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='likes_kk',
            field=models.CharField(default='Лайков в тиктоке', max_length=100, null=True, verbose_name='Заголовок лайков'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='likes_ru',
            field=models.CharField(default='Лайков в тиктоке', max_length=100, null=True, verbose_name='Заголовок лайков'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='partners_en',
            field=models.CharField(default='Партнеры', max_length=100, null=True, verbose_name='Заголовок партнеры'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='partners_kk',
            field=models.CharField(default='Партнеры', max_length=100, null=True, verbose_name='Заголовок партнеры'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='partners_ru',
            field=models.CharField(default='Партнеры', max_length=100, null=True, verbose_name='Заголовок партнеры'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='projects_en',
            field=models.CharField(default='Проекты', max_length=100, null=True, verbose_name='Поле проекты'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='projects_kk',
            field=models.CharField(default='Проекты', max_length=100, null=True, verbose_name='Поле проекты'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='projects_ru',
            field=models.CharField(default='Проекты', max_length=100, null=True, verbose_name='Поле проекты'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='statistics_en',
            field=models.CharField(default='Цифры громче слов', max_length=100, null=True, verbose_name='Заголовок статистики'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='statistics_kk',
            field=models.CharField(default='Цифры громче слов', max_length=100, null=True, verbose_name='Заголовок статистики'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='statistics_ru',
            field=models.CharField(default='Цифры громче слов', max_length=100, null=True, verbose_name='Заголовок статистики'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='subscribers_en',
            field=models.CharField(default='Подписчиков', max_length=100, null=True, verbose_name='Заголовок подписчиков'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='subscribers_kk',
            field=models.CharField(default='Подписчиков', max_length=100, null=True, verbose_name='Заголовок подписчиков'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='subscribers_ru',
            field=models.CharField(default='Подписчиков', max_length=100, null=True, verbose_name='Заголовок подписчиков'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='views_en',
            field=models.CharField(default='Просмотров в месяц', max_length=100, null=True, verbose_name='Заголовок просмотров'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='views_kk',
            field=models.CharField(default='Просмотров в месяц', max_length=100, null=True, verbose_name='Заголовок просмотров'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='views_ru',
            field=models.CharField(default='Просмотров в месяц', max_length=100, null=True, verbose_name='Заголовок просмотров'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='who_are_we_desc_en',
            field=models.TextField(null=True, verbose_name='Кто мы описание'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='who_are_we_desc_kk',
            field=models.TextField(null=True, verbose_name='Кто мы описание'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='who_are_we_desc_ru',
            field=models.TextField(null=True, verbose_name='Кто мы описание'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='who_are_we_en',
            field=models.CharField(default='Кто мы?', max_length=100, null=True, verbose_name='Поле кто мы'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='who_are_we_kk',
            field=models.CharField(default='Кто мы?', max_length=100, null=True, verbose_name='Поле кто мы'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='who_are_we_ru',
            field=models.CharField(default='Кто мы?', max_length=100, null=True, verbose_name='Поле кто мы'),
        ),
        migrations.AddField(
            model_name='people',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='people',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='people',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='people',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='people',
            name='position_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='people',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя проекта'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='title_en',
            field=models.CharField(default='Проекты', max_length=255, null=True, verbose_name='Заголовок страницы проекты'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='title_kk',
            field=models.CharField(default='Проекты', max_length=255, null=True, verbose_name='Заголовок страницы проекты'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='title_ru',
            field=models.CharField(default='Проекты', max_length=255, null=True, verbose_name='Заголовок страницы проекты'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='age_en',
            field=models.CharField(default='Возраст: ', max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='age_kk',
            field=models.CharField(default='Возраст: ', max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='age_ru',
            field=models.CharField(default='Возраст: ', max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='button_en',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Кнопка смотреть сейчас'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='button_kk',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Кнопка смотреть сейчас'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='button_ru',
            field=models.CharField(default='Смотреть сейчас', max_length=100, null=True, verbose_name='Кнопка смотреть сейчас'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='genre_en',
            field=models.CharField(default='Жанр: ', max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='genre_kk',
            field=models.CharField(default='Жанр: ', max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='genre_ru',
            field=models.CharField(default='Жанр: ', max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='language_en',
            field=models.CharField(default='Язык: ', max_length=100, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='language_kk',
            field=models.CharField(default='Язык: ', max_length=100, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='language_ru',
            field=models.CharField(default='Язык: ', max_length=100, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='series_number_en',
            field=models.CharField(default='Кол-во серий: ', max_length=100, null=True, verbose_name='Кол-во серий'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='series_number_kk',
            field=models.CharField(default='Кол-во серий: ', max_length=100, null=True, verbose_name='Кол-во серий'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='series_number_ru',
            field=models.CharField(default='Кол-во серий: ', max_length=100, null=True, verbose_name='Кол-во серий'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='projects_en',
            field=models.CharField(default='Работы', max_length=100, null=True, verbose_name='Заголовок работы'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='projects_kk',
            field=models.CharField(default='Работы', max_length=100, null=True, verbose_name='Заголовок работы'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='projects_ru',
            field=models.CharField(default='Работы', max_length=100, null=True, verbose_name='Заголовок работы'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='title_en',
            field=models.CharField(default='Королева двора', max_length=100, null=True, verbose_name='Заголовок проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='title_kk',
            field=models.CharField(default='Королева двора', max_length=100, null=True, verbose_name='Заголовок проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilmspage',
            name='title_ru',
            field=models.CharField(default='Королева двора', max_length=100, null=True, verbose_name='Заголовок проекта'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='first_product_desc_en',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='first_product_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='first_product_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='first_product_en',
            field=models.CharField(default='Видео для социальных сетей', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='first_product_kk',
            field=models.CharField(default='Видео для социальных сетей', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='first_product_ru',
            field=models.CharField(default='Видео для социальных сетей', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='fourth_product_desc_en',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='fourth_product_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='fourth_product_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='fourth_product_en',
            field=models.CharField(default='Анимация (CGI)', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='fourth_product_kk',
            field=models.CharField(default='Анимация (CGI)', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='fourth_product_ru',
            field=models.CharField(default='Анимация (CGI)', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='offer_en',
            field=models.TextField(null=True, verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='offer_kk',
            field=models.TextField(null=True, verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='offer_ru',
            field=models.TextField(null=True, verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='second_product_desc_en',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='second_product_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='second_product_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='second_product_en',
            field=models.CharField(default='Среднемасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='second_product_kk',
            field=models.CharField(default='Среднемасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='second_product_ru',
            field=models.CharField(default='Среднемасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='third_product_desc_en',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='third_product_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='third_product_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='third_product_en',
            field=models.CharField(default='Крупномасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='third_product_kk',
            field=models.CharField(default='Крупномасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='third_product_ru',
            field=models.CharField(default='Крупномасштабный продакшн', max_length=100, null=True, verbose_name='Заголовок первой услуги'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='title_en',
            field=models.CharField(default='Видеопродакшн', max_length=100, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='title_kk',
            field=models.CharField(default='Видеопродакшн', max_length=100, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='title_ru',
            field=models.CharField(default='Видеопродакшн', max_length=100, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='what_we_filming_en',
            field=models.CharField(default='Что мы снимаем', max_length=100, null=True, verbose_name='Заголовок что мы снимаем'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='what_we_filming_kk',
            field=models.CharField(default='Что мы снимаем', max_length=100, null=True, verbose_name='Заголовок что мы снимаем'),
        ),
        migrations.AddField(
            model_name='videoproductionpage',
            name='what_we_filming_ru',
            field=models.CharField(default='Что мы снимаем', max_length=100, null=True, verbose_name='Заголовок что мы снимаем'),
        ),
        migrations.AddField(
            model_name='voice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя переводившего'),
        ),
        migrations.AddField(
            model_name='voice',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя переводившего'),
        ),
        migrations.AddField(
            model_name='voice',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя переводившего'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='learn_more',
            field=models.CharField(default='Узнать больше', max_length=100, verbose_name='Кнопка узнать больше'),
        ),
    ]
