# Generated by Django 4.1.4 on 2022-12-23 06:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0014_aboutuspage_eighth_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='header/', verbose_name='Логотип'),
        ),
    ]
