# Generated by Django 4.1.4 on 2022-12-23 09:03

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0015_alter_header_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesfilms',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='series/', verbose_name='Фото проекта'),
        ),
        migrations.AddField(
            model_name='seriesfilms',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='series/', verbose_name='Превью проекта'),
        ),
    ]
