# Generated by Django 4.1.4 on 2022-12-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0017_alter_influencer_instagram_alter_influencer_tiktok_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'Страница "О нас"', 'verbose_name_plural': 'Страница "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='animationstudiopage',
            options={'verbose_name': 'Страница "Студия анимации"', 'verbose_name_plural': 'Страница "Студия анимации"'},
        ),
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name': 'Тип интереса', 'verbose_name_plural': 'Типы интереса'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент страницы видеопродакшн', 'verbose_name_plural': 'Контент страницы видеопродакшн'},
        ),
        migrations.AlterModelOptions(
            name='dubmovies',
            options={'verbose_name': 'Дублированный фильм/мультфильм', 'verbose_name_plural': 'Дублированные фильмы/мультфильмы'},
        ),
        migrations.AlterModelOptions(
            name='dubseries',
            options={'verbose_name': 'Дублированный сериал/мультсериал', 'verbose_name_plural': 'Дублированные сериалы/мультсериалы'},
        ),
        migrations.AlterModelOptions(
            name='dubstudiopage',
            options={'verbose_name': 'Страница "Студия дубляжа"', 'verbose_name_plural': 'Страница "Студия дубляжа"'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='gamedevpage',
            options={'verbose_name': 'Страница "Разработка игр"', 'verbose_name_plural': 'Страница "Разработка игр"'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Хэдер', 'verbose_name_plural': 'Хэдер'},
        ),
        migrations.AlterModelOptions(
            name='influencer',
            options={'verbose_name': 'Страница инфлюенсера/тик-ток дома', 'verbose_name_plural': 'Страницы инфлюенсера/тик-ток дома'},
        ),
        migrations.AlterModelOptions(
            name='influencermembers',
            options={'verbose_name': 'Инфо участника дома', 'verbose_name_plural': 'Инфо участников дома'},
        ),
        migrations.AlterModelOptions(
            name='influencerspage',
            options={'verbose_name': 'Страница "Инфлюенсеры"', 'verbose_name_plural': 'Страница "Инфлюенсеры"'},
        ),
        migrations.AlterModelOptions(
            name='influncerphoto',
            options={'verbose_name': 'Фото инфлюенсера', 'verbose_name_plural': 'Фото инфлюенсера'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Люди страницы "О нас"', 'verbose_name_plural': 'Люди страницы "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectspage',
            options={'verbose_name': 'Страница "Проекты"', 'verbose_name_plural': 'Страница "Проекты"'},
        ),
        migrations.AlterModelOptions(
            name='seriesfilms',
            options={'verbose_name': 'Сериал/фильм', 'verbose_name_plural': 'Сериалы/фильмы'},
        ),
        migrations.AlterModelOptions(
            name='seriesfilmspage',
            options={'verbose_name': 'Страница "Сериалы-фильмы"', 'verbose_name_plural': 'Страница "Сериалы-фильмы"'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': 'Студия дубляжа', 'verbose_name_plural': 'Студии дубляжа'},
        ),
        migrations.AlterModelOptions(
            name='videoproductionpage',
            options={'verbose_name': 'Страница "Видеопродакшн"', 'verbose_name_plural': 'Страница "Видеопродакшн"'},
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name': 'Голос студии дубляжа', 'verbose_name_plural': 'Голоса студии дубляжа'},
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название игры'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название партнера'),
        ),
        migrations.AddField(
            model_name='studio',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название студии'),
        ),
    ]
