# Generated by Django 4.1.4 on 2022-12-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jks_site', '0018_alter_aboutuspage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.footer', verbose_name='Футер'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jks_site.header', verbose_name='Хэдер'),
        ),
    ]
